# Flow of the pipeline
# 1. Initialise the required credentials
# 2. Build stage will build the docker image
# 3. Run Terraform plan
# 4. Run Terraform apply.

#Canary Deployment(To be discussed and applied)

# 1. Create new target group
# 2. Build new docker image and push it to registry
# 3. Create new ECS Service to serve these tasks defintion
# 4. Shift little amount of traffic from ALB to newly created service
# 5. If the test is going good we can increase the traffic 
# 6. If errors are there we can delete the new service and shift all traffic to old service

.ssh: &ssh-common
  before_script:
    - mkdir -p ~/.ssh
    - eval `ssh-agent -s`
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - ssh-add - <<< "$SSH_PRIVATE_KEY"

.npm_setup: &npm_setup
  before_script:
    - npm config set registry https://registry.npmjs.org/
    - npm config set //artifactory.cimpress.io/artifactory/api/npm/npm-release-local/:_authToken=$CT_ARTIFACTORY_TOKEN
    - npm config set //artifactory.cimpress.io/artifactory/api/npm/npm-release-local/:always-auth=true
    - npm config set @cimpress-technology:registry https://artifactory.cimpress.io/artifactory/api/npm/npm-release-local/
    - chmod 644 ~/.npmrc

.tags: &tags-common
  tags:
    - docker
    - linux

stages:
  - init
  - build
  - deploy-canary
  - plan
  - deploy

intialise: 
   image: xueshanf/awscli
   stage: init
   script:
     - export SECRETS_STRING="$(aws secretsmanager get-secret-value --secret-id $AMAROK_ARTIFACTORY_TOKEN_SECRET_ARN --query SecretString --output text --region eu-west-1)"
     - echo "CT_ARTIFACTORY_TOKEN=$(jq -r '.token' <<<"$SECRETS_STRING")" >> build.env
    #  - echo "CT_ARTIFACTORY_USER=$AMAROK_ARTIFACTORY_USER" >> build.env
   artifacts:
     expire_in: 1 week
     reports:
       dotenv: build.env
   tags:
    - docker
    - linux

build-stg :
  <<: *ssh-common
  <<: *npm_setup
  <<: *tags-common
  image: node:14
  stage : build
  artifacts :
    untracked: true 
    expire_in : 1 week
  script : 
    - npm -v
    - echo "checking NODE_ENV value"
    - echo $NODE_ENV
    - npm run build:stag
    - npm ci
  variables :
    NODE_ENV : "stg"


plan-stg :
  <<: *ssh-common
  <<: *tags-common
  image: registry.gitlab.com/cimpress-technology/ff/infrastructure.ci.cd/modules/ecs-service:1.3.0
  stage : plan
  artifacts :
    untracked: true 
    expire_in : 1 week
  script : 
    - terraform -v
    - cd scripts
    - terraform init
    - terraform validate
    - terraform plan 

deploy-stg :
  <<: *ssh-common
  <<: *tags-common
  image: registry.gitlab.com/cimpress-technology/ff/infrastructure.ci.cd/modules/ecs-service:1.3.0
  stage : deploy
  when: manual
  only : 
    - master
    - main
  dependencies:
    - "build-stg"
  script : 
    - chmod +x scripts/build-image.sh
    - ./scripts/build-image.sh
    - cd scripts
    - export const TF_VAR_container_version=$CI_COMMIT_SHORT_SHA
    - terraform init
    - terraform apply --auto-approve

deploy-canary : 
  image: xueshanf/awscli
  stage: deploy-canary
  only: 
    - master
    - main
  dependencies:
    - "build-stg"
  script :
   - aws ecs create-service --cluster ecs-service-cluster-nonprod --service-name comparator_canary --task-definition sleep360:2 --desired-count 2


